const userType ={
    USER_LIST_REQUEST:"USER_LIST_REQUEST",
    USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
    USER_LIST_FAIL: "USER_LIST_FAIL",

    USER_CREATE_REQUEST:'USER_CREATE_REQUEST',
    USER_CREATE_SUCCESS:'USER_CREATE_SUCCESS',
    USER_CREATE_FAIL:'USER_CREATE_FAIL',

    USER_UPDATE_REQUEST:'USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS:'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAIL:'USER_UPDATE_FAIL',

    USER_DELETE_REQUEST:'USER_DELETE_REQUEST',
    USER_DELETE_SUCCESS:'USER_DELETE_SUCCESS',
    USER_DELETE_FAIL:'USER_DELETE_FAIL'
}

export default userType